from typing import Any

class PeftModel:
    device: Any
    @classmethod
    def from_pretrained(cls, model: Any, model_id: str, **kwargs: Any) -> PeftModel: ...
    def eval(self) -> PeftModel: ...
    def merge_and_unload(self) -> Any: ...
    def save_pretrained(self, save_directory: str, **kwargs: Any) -> None: ...
    def print_trainable_parameters(self) -> None: ...
    def generate(self, **kwargs: Any) -> Any: ...
    def __call__(self, **kwargs: Any) -> Any: ...
